### ISSUE TITLE
score with PRIDICT2.0 on existing pegRNA sequences

### ISSUE THREAD

**Issue by ov26** [uzh-dqbm-cmi/PRIDICT2#2]
Hi! I was wondering if there was a capacity to run the PRDICT2.0 scoring platform on externally designed pegRNA sequences?

**Comment by mathinic** [comment]
Hi,
There is no option to directly go from pegRNA alone to efficiency, as this would also require the target sequence and some alignment steps to figure out your intended edit.
To avoid any misalignments or wrong predictions, we do not offer this option, but rather suggest that you run PRIDICT2.0 with the standard input for the given pegRNA (NNN(X/Y)NNN) and then filter the readout based on the pegRNA.

I could however implement some guidance in the ReadMe on how to do the second step (find the pegRNA score of a specific pegRNA in the output after prediction), if this is something that would help your research? :)

Best wishes
Nicolas

**Comment by ov26** [comment]
Hi! thanks for the quick reply! To make it easier and perhaps faster is there a way to fix the pegRNA parameters when running pridict (ie only generate pegRNA with a pbs length of x), to avoid generating all possibilities and then filtering?

**Comment by mathinic** [comment]
Yes, this is possible with the current setup.
You can adapt the default range by editing the parameters at the top of the main script [pridcit2_pegRNA_design.py](https://github.com/uzh-dqbm-cmi/PRIDICT2/blob/main/pridict2_pegRNA_design.py) (screenshot below).

E.g. if you are only interested in PBS length 13, you can replace the default parameters with `[13]` (or alternatively "`range(13,14)`"). Same is possible for RTT overhang length. Then PRIDICT2.0 will only predict pegRNA with these parameters, making it more efficient.

Does that help, or would there be a large need to being able to define PBS/RTT length for each target separately, e.g. as an argument in the batch input file?

![image](https://github.com/user-attachments/assets/33b4b861-cf94-40f6-97e4-7055e070415e)
